---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-credentials
  namespace: open-webui
spec:
  encryptedData:
    OPENAI_API_KEY: AgB2FIrTqdkVkoNP/QCcaNSZVL0M/UiIoA1rj3WP+C3vhnNPMd8eBHWXhh72cxRDYiAbAtpd4iA+70rHfohSzenjU/Cw9EOcSRpGdjt5Ykgh3RBsEwKSWxkcr78vDxcbHcDQKWez/sLE8ofdONiDzeS4XR5RbdO8d0CnTpnta6y1JwZIERAWCjMao43F5trJUaj2JBaqwntfftMIgzALeJm+qf0mk5hXg/5cRwVSBEHf7zISsjVvG9vjue8L1v0RE/QicYHnzz99Cg7rh/zmkQ7W+cT0rXBejqHQFVtXrK+nUvMEQDpz+rgh2JBE7Z2tYS/cKPUXlWkFPZSOGpytmKLrrVp5gdCKpfZup8uP3sNIILBZmQM1HAnOtRVU4TEONkrl+/sxk367rNW/BxEM0Nq3Eq+YhDejV8URPdDy2AvrHM6Q4cPItLFnzdyctgtTxb0Tlf6Qo/wVsLVGm7kk7qmHDbMFpKMz6PWgZYcaUp0mH7wxCXuFnlYiejd9UVUDK2mFFu6gVVwO7BPQXgQLdaBpPnPSxnfIhU8OgSYgLRlRQRnFA1KwKVgifBjnzUtzoganl1S+IaB40AS0ZPQw0wsrMEc/pGkQXSoz/G3W72JtpLsb6X5A2ODgIbpZTCyLfXbaKxs1ipcIQJTFkv0893tPUs9LJm+NCReWSxKd/VyNhJ5RIYl8ZIgHpyL0Cr0cPb6cDJxmePW0o+nFaW0KKHzBdg==
  template:
    metadata:
      name: open-webui-credentials
      namespace: open-webui
