---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-credentials
  namespace: open-webui
spec:
  encryptedData:
    OPENAI_API_KEY: AgBc9lV/828HWU5qugNhc/DNG0hqRczslg2AQaCH3lnS+ylGl5xdSz5ypUQ++AupxTvpPbkhJdS+NsDex1EnrTdZI8MIssIgaTWqUcYBnCIv4h7S43WXI28P1XM8CZo0RfbdJUcmxQf6KnIR++i9YY0ynymmqWlDAXS48Gi1J0OaQ+6QejN33VULL5Gcd1UIR39SJOqamcmaXG4PLPGU4MnOflNE9QdJMdzrq2PyEEavJPQ7vawY7Kv6I+ww5i2lKMZxHbWoMibedlHe/kZ59NJ0BioTc7cx81FDCnNgmRgU1Hvh2S3K4safYMfNyE8AUbvE5ybe09ov/iUsIqsUdSUiNFRtaqh0jBSCvRfPKoGmnOQo/T7d6Sy3jDULBye5fzN33FwupUQt1WRadolTHvtO5Czqn+mT2lkLQKruxz13n4wEuulR2it/LdFUa2BdLtxDBfjTLhABSp/Fyrleo0GTI26Zlx1Mdj1GEedxLyceWRNzjYA0TM7r59NkiKqfFgq6z+GGxOU+0VmKxDkQqa/QhWz3AflvUy7eRn0er3XkhsdmRQ7huyMGtOM6WLnX2RHQJQT5yC4HyaKThAgBRXQYkB9lNBTXXXHjIRHBJdyvnz3oV08dfEt0otvA7Id1O/Pc0n2KoP9nXXiHKink77hmVnYAlFFPo1uwHMGguoC38+z0sZOUwQZT/Ymi2eTD1gQ=
  template:
    metadata:
      name: open-webui-credentials
      namespace: open-webui
