---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-token
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgAoGVnHngMHN0BcBU4Ob0D1r36ojTCi/vsgVUjafJ+5OOJcY+58I38+Z39ij3Oql5IoXpm8zsHsdncwhmu4HhLgoaXwcPdvzoBpLsn6F/kt6ZWUT5yiuoZMDbeHF1ADBfSlRSAvCRSQNKt5I2amyhCpNfgzC0NUkpAizLKD9CiQq/YiOlrWteOFLlsopTlCe3vDxsjPZVwoWueQDSMgSrDFOZZVTL3LEejq++WEuciZJH7ROXLZTmSro0RiLbpoKJzii1cT1yxVBjZMiaANNKcoBO2AakaT9p1WJhnlcyv2GhUyt9DcM7FY2FepMMt3qs5UXWvySi7PV6hrBV9jnwqd0jQrUVVzpFo1MDB6a5lhXvTKS/folG4GKkg7rICPfHwuken9xUKDcYP4fItJcs+g0mkAjGhqIGlg/SyOTO0dUhEFt0DzLeV7OEwBmEe/kRAUqZ3FNu/4/Z1T9Q4lSqXKauwFn9TreyjpPxi7rCE5lssg2hr6z4pgSZ1I0YsTE3YQ+DiSYz8KxPqJR6uPi4zYS2zwlVHD2tKKtF2D5dCIlmXZFmPptC3ii1ahJatMR5hCSTIIqNbBdjIAQDmCdnTf81EQto+/dbPnzh3iNvPDFnFdlzanWJHwTLlNc/9UQy9BJGuZdEbXWTfk7C7aRJpnyvaAD42/CX/J75HCGTNdZ+fuVy8Mw2eIOrXXlYfY0lOWKr4CFLcbeFaEpK28K2WydOT9vZWj2ycNwb//N3dZ28VpE3A6YtABhwBvTtVUqhw/HkGWsKPNftQ5Kf53/Ejk/Y3rSrIKlU+1AQ4N47RP6uV6rNAyL/sHqkRpSkQ=
  template:
    metadata:
      name: renovate-token
      namespace: renovate
