---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgCO4U5TeFIeNvLeGB9BAvy/0KRdm2bcVOCV6ap0p+4OwMgW8soA2bWOXGya1HTKX8t4PhdzKEFy5YhmteeB9OFAocFGyGxc8O9uA28zovR/MMhjgveFzbYTHLDf5D8wDUxF6RLuCjWxuNHgQ0K7+YR7hUf2q7fDsoRsjdZVHETqehGampuTRuff/cdA08nffvSxJGYhiFX/yH8vXYe9sPod4VkW+eqqZ3riHl1ctO9Fzb0HTSL2/vIjKA05wcFY84XvN38P6Hynjp+vo0cLlmRiVTV02pQ3IlKdWPpCYL1J7hZX5Zi8Dh9H8cXSNWx27X8eus3qm44x7rt/OuAXls59fT16xgN0kRsOy4PYOzj8NSgfnv8ZubpcTY0mzOTCg9R8PRbx3eg5tzip9fHM/K6gyqWVrNcV1jzo+wT/m/d78X33xk8IdeaDkPIx8v6w5XYksxHqjMQzFr2s9o2UFdHzfLB98wX3m9DP5hkzRwdq8ktHmvIvtnV7+W+diUZvcGGKP8yF7XErUyzs33shOFWjlwTidi3952Vu+6nkKoH8E0SkFfON0cqXglXKLMbuHgMXHZbEctIRtR9ZggaSSWb5iBET4XIh9qqfdaI3wuo2rm2lxdwDOZD1rYFBeMElCiZclv5hhn5Sg8aHF8jgafQrckpkcjnOEX96qIwqqSyhzFEWF80gA5AP4lN7C4nT8zEWTasRtU9n/cxRZ3H2DRdLzXGBO41Bm1F3k3H8bTtp2Zrjgs4vI0NTNCvnZVI3XX0rZ0KPz5EwDuxz/A6RLeX5
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
