image:
  tag: "latest"

domain: "https://vaultwarden.tailbd291c.ts.net"

storage:
  data:
    name: vaultwarden-data
    size: 2Gi
    class: local-path
    accessMode: ReadWriteOnce

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.0.205"

adminToken:
  existingSecret: vaultwarden-secret
  existingSecretKey: ADMIN_TOKEN

signupsAllowed: true
signupsVerify: false
showPassHint: "false"
