image:
  tag: "1.37.2"

domain: "https://vaultwarden.tailbd291c.ts.net"

storage:
  data:
    name: vaultwarden-data
    size: 2Gi
    class: longhorn
    accessMode: ReadWriteOnce

service:
  type: LoadBalancer
  # IP fixed via metallb/ipaddresspool.yaml (vaultwarden-pool: 192.168.0.205)

adminToken:
  existingSecret: vaultwarden-secret
  existingSecretKey: ADMIN_TOKEN

signupsAllowed: false
showPassHint: "false"
