apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-backups-nfs-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: forgejo
    name: forgejo-backups
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
  nfs:
    server: 192.168.0.40
    path: "/k3s-storage/forgejo/backups"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-backups
  namespace: forgejo
spec:
  storageClassName: ""
  volumeName: forgejo-backups-nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
