apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      spec:
        type: LoadBalancer
    ports:
      web:
        port: 8000
        exposedPort: 80
      websecure:
        port: 8443
        exposedPort: 443
