apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-prometheus-token
  namespace: home-assistant
spec:
  encryptedData:
    token: AgCkHF7cRT7IXWWqbSqkLd7APr7hYjINe+lfIlpRtWgm5SE8lHgUSLhFau/cPBS5beDHpZU2GoJgt5YPBTR94zn46OhutNWQ5wZt5zIdgRlzIzz+ucinhf3hLanDK7hpCAWputoIrtYshk33PVYnm07d6ifXHkuqvAISi02CsYzbSWKwWgMnASmD77SoPc3bNJrgpNY32ErekRrm2Q6DFlMTQLXgK7IsYQDsoeV9qLR1iKwFR5byHjnNoSLit/N0IjkRlHJVTLD3OK/Q41iiptD4DmftD2TEzFPa3aOVUxt2PD5rIa7z88VIYqNvqoLZQwq1o0CnK33Whs7gTJF4O5inAbqG+eHYIt6IbBTQJZ4QLt3kxk+PkDFHjifrKp/WTRq+kJPpyy5trqnwGX3v6TxmvJzjPjzDeRJu96YsM40Vu8hGnWH4gN3zUat2MxDt7oj8Qqjh9Th/9hUfNjct800A3NYtJXVAQnrU0vSfm9v5Pi359I2vdXz+fsTLwcse2tYmjNyV+DTAEaWaVhEPlQaGDP54CyVF1LuvSvmzqyqwtHKQ3v2H4M31oNbElGbr1jrynarDVDJm1qEKYvP1ZIiqH077tzflmVvequAnIJT1udD1hou312MlAIyRyvQEVUN/aqHEEvGVpkTilQXIDo4aj4sfsuk6B6ZLk7ErerHUpdih/+tj6kw71uHhuSN9O9mNyBKTFWJnve99i5Bw+DWlew1gSU+MLIOFF2Nn2HajlP3VtPWPey9MUf/ee7jwE+u30YAvX2ujnFPJRSAhXps9jWXbeHFnqQ9VQN0f/TPmWir5lddDF7qdM1pCv++MQhBELtO1ULUw5tOKpo3OcQwpwQmJOVZ1+ngsbdZ6I1FYFP1oAvMhE+73AalEyKHypqJkwxTUy/iRicKWe7Vjzpee8YoGKxeSkA32T0qcQHFUevw7sl1K3x0=
  template:
    metadata:
      name: home-assistant-prometheus-token
      namespace: home-assistant
