service:
  type: LoadBalancer
  port: 8123
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.0.204"

persistence:
  enabled: true
  storageClass: local-path
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

configuration:
  enabled: true
  forceInit: true
  trusted_proxies:
    - 10.42.0.0/16
    - 10.43.0.0/16
  templateConfig: |-
    # Loads default set of integrations. Do not remove.
    default_config:
    http:
      use_x_forwarded_for: true
      trusted_proxies:
      {{- range .Values.configuration.trusted_proxies }}
        - {{ . }}
      {{- end }}
    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes
    # Expose metrics for Prometheus ServiceMonitor
    prometheus:
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

hostNetwork: false

addons:
  codeserver:
    enabled: false

serviceMonitor:
  enabled: true
  bearerToken:
    secretName: home-assistant-prometheus-token
    secretKey: token
