apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel-ipam-cleanup
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flannel-ipam-cleanup
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flannel-ipam-cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel-ipam-cleanup
subjects:
  - kind: ServiceAccount
    name: flannel-ipam-cleanup
    namespace: kube-system
