apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: forgejo
  sources:
    - repoURL: code.forgejo.org/forgejo-helm
      chart: forgejo
      targetRevision: 17.0.0
      helm:
        valueFiles:
          - $repo/forgejo/values.yaml
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      ref: repo
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      path: forgejo
      directory:
        include: '{namespace.yaml,sealed-secret.yaml,tailscale-ingress.yaml,tailscale-ssh-service.yaml,nfs-pv-pvc.yaml,forgejo-dump-cronjob.yaml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
