apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  sources:
    # Helm chart
    - repoURL: https://pajikos.github.io/home-assistant-helm-chart/
      chart: home-assistant
      targetRevision: '*'
      helm:
        valueFiles:
          - $repo/home-assistant/values.yaml
    # Git repo for values file reference
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      ref: repo
    # Raw manifests (Tailscale ingress)
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      path: home-assistant
      directory:
        include: '{tailscale-ingress.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
