apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: '*'
      helm:
        valueFiles:
          - $repo/longhorn/values.yaml
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      ref: repo
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      path: longhorn
      directory:
        include: '{tailscale-ingress.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
