apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  sources:
    # NextCloud Helm chart
    - repoURL: https://nextcloud.github.io/helm/
      chart: nextcloud
      targetRevision: 9.0.5
      helm:
        valueFiles:
          - $repo/nextcloud/values.yaml
    # Git repo for values file reference
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      ref: repo
    # Raw manifests
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      path: nextcloud
      directory:
        include: '{namespace.yaml,postgresql.yaml,redis.yaml,nfs-pv-pvc.yaml,sealed-secret.yaml,tailscale-ingress.yaml,pg-backup-cronjob.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
