apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  project: default
  sources:
    # Helm chart
    - repoURL: ghcr.io/renovatebot/charts
      chart: renovate
      targetRevision: '*'
      helm:
        valueFiles:
          - $repo/renovate/values.yaml
    # Git repo for values file reference
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      ref: repo
    # Raw manifests (SealedSecret)
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      path: renovate
      directory:
        include: '{sealed-secret.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
