apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  sources:
    # Helm chart
    - repoURL: https://guerzon.github.io/vaultwarden
      chart: vaultwarden
      targetRevision: '*'
      helm:
        valueFiles:
          - $repo/vaultwarden/values.yaml
    # Git repo for values file reference
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      ref: repo
    # Raw manifests (Tailscale ingress + SealedSecret)
    - repoURL: https://github.com/benkim0414/homelab.git
      targetRevision: HEAD
      path: vaultwarden
      directory:
        include: '{sealed-secret.yaml,tailscale-ingress.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
