# kube-vip Helm chart values
# Chart: kube-vip/kube-vip
# Repo: https://kube-vip.github.io/helm-charts

image:
  tag: "v1.0.4"

config:
  address: "192.168.0.10"

env:
  vip_interface: "eth0"
  cp_enable: "true"
  svc_enable: "false"
  lb_enable: "false"
  vip_leaderelection: "true"
  vip_leasename: "plndr-cp-lock"
  vip_leaseduration: "15"
  vip_renewdeadline: "10"
  vip_retryperiod: "2"

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - NET_RAW
      - SYS_TIME
    drop:
      - ALL

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
